version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: myDatabase
      MONGO_INITDB_ROOT_USERNAME: myUser
      MONGO_INITDB_ROOT_PASSWORD: myPassword
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: nosql-auth-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: myDatabase
      SPRING_DATA_MONGODB_USERNAME: myUser
      SPRING_DATA_MONGODB_PASSWORD: myPassword
    volumes:
      - .:/app
    depends_on:
      - mongo

volumes:
  mongo-data:
